# Generated by Django 4.0.4 on 2022-05-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_no', models.CharField(blank=True, max_length=10, null=True)),
                ('semester', models.CharField(blank=True, max_length=1, null=True)),
                ('about', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='student_db',
            name='sl_no',
        ),
        migrations.AddField(
            model_name='student_db',
            name='reg_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student_db',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
