# Generated by Django 4.0.4 on 2022-05-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_fname_sem1students_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sem2students',
            options={'verbose_name_plural': 'Sem-2 Students'},
        ),
        migrations.AlterModelOptions(
            name='sem3students',
            options={'verbose_name_plural': 'Sem-3 Students'},
        ),
        migrations.AlterModelOptions(
            name='sem4students',
            options={'verbose_name_plural': 'Sem-4 Students'},
        ),
        migrations.AlterModelOptions(
            name='sem5students',
            options={'verbose_name_plural': 'Sem-5 Students'},
        ),
        migrations.AlterModelOptions(
            name='sem6students',
            options={'verbose_name_plural': 'Sem-6 Students'},
        ),
        migrations.RenameField(
            model_name='sem1students',
            old_name='reg_no',
            new_name='ern',
        ),
        migrations.RenameField(
            model_name='sem2students',
            old_name='reg_no',
            new_name='ern',
        ),
        migrations.RenameField(
            model_name='sem3students',
            old_name='reg_no',
            new_name='ern',
        ),
        migrations.RenameField(
            model_name='sem4students',
            old_name='reg_no',
            new_name='ern',
        ),
        migrations.RenameField(
            model_name='sem5students',
            old_name='reg_no',
            new_name='ern',
        ),
        migrations.RenameField(
            model_name='sem6students',
            old_name='reg_no',
            new_name='ern',
        ),
        migrations.RemoveField(
            model_name='sem1students',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='sem1students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sem2students',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='sem2students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sem3students',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='sem3students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sem4students',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='sem4students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sem5students',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='sem5students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='sem6students',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='sem6students',
            name='gender',
        ),
        migrations.AddField(
            model_name='sem1students',
            name='class_details',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem1students',
            name='contact_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem1students',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem1students',
            name='roll_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem2students',
            name='class_details',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem2students',
            name='contact_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem2students',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem2students',
            name='roll_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem3students',
            name='class_details',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem3students',
            name='contact_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem3students',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem3students',
            name='roll_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem4students',
            name='class_details',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem4students',
            name='contact_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem4students',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem4students',
            name='roll_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem5students',
            name='class_details',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem5students',
            name='contact_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem5students',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem5students',
            name='roll_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem6students',
            name='class_details',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem6students',
            name='contact_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='sem6students',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='sem6students',
            name='roll_no',
            field=models.IntegerField(default=None),
        ),
    ]
