# Generated by Django 4.0.4 on 2022-05-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_sem2students_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sem1students',
            options={'verbose_name_plural': 'Sem-1 Students'},
        ),
    ]
