# Generated by Django 4.0.4 on 2022-05-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_feedback_remove_student_db_sl_no_student_db_reg_no_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='date',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.CharField(max_length=1),
        ),
        migrations.CreateModel(
            name='Sem1Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('semester', models.CharField(default=1, max_length=20)),
                ('subject', models.CharField(choices=[('ST', 'ST'), ('NSM', 'NSM'), ('CC', 'CC'), ('ST Lab', 'ST Lab'), ('NS Lab', 'NS Lab')], default=None, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student_db')),
            ],
        ),
    ]
