# Generated by Django 4.0.4 on 2022-05-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_timetable_date_timetable_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem1attendance',
            name='subject',
            field=models.CharField(choices=[('ENGINEERING MATHEMATICS', 'ENGINEERING MATHEMATICS'), ('FUNDAMENTALS OF COMPUTER', 'FUNDAMENTALS OF COMPUTER'), ('FUNDAMENTALS OF ELECTRICAL & ELECTRONICS ENGINEERING LAB', 'FUNDAMENTALS OF ELECTRICAL & ELECTRONICS ENGINEERING LAB'), ('IT SKILLS LAB', 'IT SKILLS LAB'), ('ENVIRONMENT SUSTAINABILITY', 'ENVIRONMENT SUSTAINABILITY')], default=None, max_length=255),
        ),
    ]
