# Generated by Django 4.0.4 on 2022-05-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_sem6attendance_sem5attendance_sem4attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem2attendance',
            name='semester',
            field=models.CharField(default=2, max_length=20),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='semester',
            field=models.CharField(default=3, max_length=20),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='semester',
            field=models.CharField(default=4, max_length=20),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='semester',
            field=models.CharField(default=5, max_length=20),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='semester',
            field=models.CharField(default=6, max_length=20),
        ),
    ]
