# Generated by Django 4.0.4 on 2022-05-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_sem1attendance_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sem1attendance',
            old_name='reg_no',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='sem2attendance',
            old_name='reg_no',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='sem3attendance',
            old_name='reg_no',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='sem4attendance',
            old_name='reg_no',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='sem5attendance',
            old_name='reg_no',
            new_name='roll',
        ),
        migrations.RenameField(
            model_name='sem6attendance',
            old_name='reg_no',
            new_name='roll',
        ),
    ]
