# Generated by Django 4.0.4 on 2022-05-14 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_rename_reg_no_sem1attendance_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem1attendance',
            name='semester',
            field=models.CharField(default=1, max_length=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sem1attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=7),
        ),
        migrations.AlterField(
            model_name='sem2attendance',
            name='semester',
            field=models.CharField(default=2, max_length=1, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='sem2attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=7),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='semester',
            field=models.CharField(default=3, max_length=1, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=7),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='semester',
            field=models.CharField(default=4, max_length=1, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=7),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='semester',
            field=models.CharField(default=5, max_length=1, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=7),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='semester',
            field=models.CharField(default=6, max_length=1, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=7),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='room_no',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(max_length=70),
        ),
    ]
