# Generated by Django 4.0.4 on 2022-05-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_sem1attendance_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sem1attendance',
            options={'verbose_name_plural': 'Sem-1 Attendance'},
        ),
        migrations.AlterModelOptions(
            name='sem2attendance',
            options={'verbose_name_plural': 'Sem-2 Attendance'},
        ),
        migrations.AlterModelOptions(
            name='sem3attendance',
            options={'verbose_name_plural': 'Sem-3 Attendance'},
        ),
        migrations.AlterModelOptions(
            name='sem4attendance',
            options={'verbose_name_plural': 'Sem-4 Attendance'},
        ),
        migrations.AlterModelOptions(
            name='sem5attendance',
            options={'verbose_name_plural': 'Sem-5 Attendance'},
        ),
        migrations.AlterModelOptions(
            name='sem6attendance',
            options={'verbose_name_plural': 'Sem-6 Attendance'},
        ),
    ]
