# Generated by Django 4.0.4 on 2022-05-14 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_sem1attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem1attendance',
            name='semester',
            field=models.IntegerField(default=1, max_length=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sem2attendance',
            name='semester',
            field=models.IntegerField(default=2, max_length=1, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='semester',
            field=models.IntegerField(default=3, max_length=1, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='semester',
            field=models.IntegerField(default=4, max_length=1, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='semester',
            field=models.IntegerField(default=5, max_length=1, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='semester',
            field=models.IntegerField(default=6, max_length=1, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
