# Generated by Django 4.0.4 on 2022-05-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_sem1attendance_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
