# Generated by Django 4.0.4 on 2022-07-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_sem1attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem1attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=7),
        ),
    ]
