# Generated by Django 4.0.4 on 2022-07-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_sem1attendance_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem1attendance',
            name='roll',
            field=models.IntegerField(),
        ),
    ]
