# Generated by Django 4.0.4 on 2022-07-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_alter_sem1attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem1attendance',
            name='status',
            field=models.CharField(default='Absent', max_length=7),
        ),
        migrations.AlterField(
            model_name='sem2attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sem2attendance',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sem2attendance',
            name='status',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='status',
            field=models.CharField(max_length=7),
        ),
    ]
