# Generated by Django 4.0.4 on 2022-07-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_alter_sem1attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sem1attendance',
            options={'verbose_name_plural': 'Sem-1 Attendances'},
        ),
        migrations.AlterModelOptions(
            name='sem2attendance',
            options={'verbose_name_plural': 'Sem-2 Attendances'},
        ),
        migrations.AlterModelOptions(
            name='sem3attendance',
            options={'verbose_name_plural': 'Sem-3 Attendances'},
        ),
        migrations.AlterModelOptions(
            name='sem4attendance',
            options={'verbose_name_plural': 'Sem-4 Attendances'},
        ),
        migrations.AlterModelOptions(
            name='sem5attendance',
            options={'verbose_name_plural': 'Sem-5 Attendances'},
        ),
        migrations.AlterModelOptions(
            name='sem6attendance',
            options={'verbose_name_plural': 'Sem-6 Attendances'},
        ),
        migrations.AlterField(
            model_name='sem1attendance',
            name='status',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sem1attendance',
            name='subject',
            field=models.CharField(choices=[('ENGINEERING MATHEMATICS', 'ENGINEERING MATHEMATICS'), ('FUNDAMENTALS OF COMPUTER', 'FUNDAMENTALS OF COMPUTER'), ('FUNDAMENTALS OF ELECTRICAL & ELECTRONICS ENGINEERING LAB', 'FUNDAMENTALS OF ELECTRICAL & ELECTRONICS ENGINEERING LAB'), ('IT SKILLS LAB', 'IT SKILLS LAB'), ('ENVIRONMENT SUSTAINABILITY', 'ENVIRONMENT SUSTAINABILITY')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sem2attendance',
            name='subject',
            field=models.CharField(choices=[('PROJECT MANAGEMENT SKILLS', 'PROJECT MANAGEMENT SKILLS'), ('STATISTICS AND ANALYSIS', 'STATISTICS AND ANALYSIS'), ('COMMUNICATION SKILLS', 'COMMUNICATION SKILLS'), ('CAEG (COMPUTER AIDED ENGINEERING GRAPHICS)', 'CAEG (COMPUTER AIDED ENGINEERING GRAPHICS)'), ('MULTIMEDIA & ANIMATION', 'MULTIMEDIA & ANIMATION'), ('KANNADA-1', 'KANNADA-1')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='subject',
            field=models.CharField(choices=[('PYTHON PROGRAMMING', 'PYTHON PROGRAMMING'), ('COMPUTER HARDWARE, MAINTENANCE AND ADMINISTRATION', 'COMPUTER HARDWARE, MAINTENANCE AND ADMINISTRATION'), ('COMPUTER NETWORKS', 'COMPUTER NETWORKS'), ('DATABASE SYSTEM CCONCEPTS & PL/SQL', 'DATABASE SYSTEM CCONCEPTS & PL/SQL'), ('ಸಾಹಿತ್ಯ ಸಿಂಚನ -II/ ಬಳಕೆ ಕನನಡ-II', 'ಸಾಹಿತ್ಯ ಸಿಂಚನ -II/ ಬಳಕೆ ಕನನಡ-II')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='status',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='subject',
            field=models.CharField(choices=[('DATA STRUCTURES WITH PYTHON', 'DATA STRUCTURES WITH PYTHON'), ('OPERATING SYSTEM & ADMINISTRATION', 'OPERATING SYSTEM & ADMINISTRATION'), ('OBJECT ORIENTED PROGRAMMING & DESIGN WITH JAVA', 'OBJECT ORIENTED PROGRAMMING & DESIGN WITH JAVA'), ('Software Engineering principles and practices', 'Software Engineering principles and practices'), ('Indian Constitution', 'Indian Constitution')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='status',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='subject',
            field=models.CharField(choices=[('placeholder', 'placeholder')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='status',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='subject',
            field=models.CharField(choices=[('placeholder', 'placeholder')], max_length=255),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
