# Generated by Django 4.0.4 on 2022-07-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_alter_sem1attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem1attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='subject',
            field=models.CharField(choices=[('Cloud Computing ', 'Cloud Computing ')], max_length=255),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='subject',
            field=models.CharField(choices=[('Inplant Training/Project Work', 'Inplant Training/Project Work')], max_length=255),
        ),
    ]
