# Generated by Django 4.0.4 on 2022-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_alter_sem1attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem2attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sem3attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sem4attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sem5attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sem6attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
